name: Publish Speiseplan to Rocket.Chat

on:
  schedule:
    - cron: "30 7 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: publish-speiseplan

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: 'pip'
      #- name: Install ghostscript
      #  run: sudo apt-get install ghostscript python3-tk
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run
        run: python publish_speiseplan.py
        env:
          INTRA_URL: ${{ secrets.INTRA_URL }}
          INTRA_PASS: ${{ secrets.INTRA_PASS }}
          INTRA_USER: ${{ secrets.INTRA_USER }}
          ROCKETCHAT_ID: ${{ secrets.ROCKETCHAT_ID }}
          ROCKETCHAT_TOKEN: ${{ secrets.ROCKETCHAT_TOKEN }}
          ROCKETCHAT_URL: ${{ secrets.ROCKETCHAT_URL }}
          IMGBB_KEY: ${{ secrets.IMGBB_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
